# Generated by Django 5.1.1 on 2024-09-25 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barber",
            name="email",
        ),
        migrations.RemoveField(
            model_name="barber",
            name="password",
        ),
        migrations.RemoveField(
            model_name="barber",
            name="username",
        ),
        migrations.AddField(
            model_name="barber",
            name="user",
            field=models.OneToOneField(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
