# Generated by Django 5.1.1 on 2024-09-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_alter_barber_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("confirmed", "Confirmed"), ("canceled", "Canceled")],
                default="confirmed",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="is_booked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_time",
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("barber", "day_of_week", "start_time")},
        ),
    ]
