# Generated by Django 5.1.1 on 2024-09-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_rename_phone_number_customuser_customer_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="customer_phone",
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
